import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
const API_KEY=import.meta.env.VITE_API_KEY||"change-me";
const headers={"X-API-Key":API_KEY};
const getJson=path=>fetch(`${API}/api/${path}`,{headers}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()});
function App(){const[page,setPage]=useState("Dashboard"),[data,setData]=useState({providers:[],targets:[],scenarios:[],strategies:[],configs:[],campaigns:[],runs:[],findings:[],summary:{total:0,critical:0,high:0,medium:0,low:0,average_score:0,open:0}}),[form,setForm]=useState({name:"",target_id:"",provider_ids:[],scenario_ids:[],strategy_id:"",attempts:1}),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{try{const [providers,targets,scenarios,strategies,configs,campaigns,findings,summary]=await Promise.all([getJson("providers"),getJson("targets"),getJson("scenarios"),getJson("strategies"),getJson("test-configurations"),getJson("campaigns"),getJson("findings"),getJson("findings/summary")]);setData(d=>({...d,providers,targets,scenarios,strategies,configs,campaigns,findings,summary}));if(!form.target_id&&targets[0])setForm(f=>({...f,target_id:String(targets[0].id)}));if(!form.strategy_id&&strategies[0])setForm(f=>({...f,strategy_id:String(strategies[0].id)}));}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);useEffect(()=>{if(page!=="Campaigns")return;const refresh=async()=>{await load();if(selected){try{setData(d=>({...d,runs:await getJson(`campaigns/${selected}/runs`)}))}catch{}}};refresh();const t=setInterval(refresh,1500);return()=>clearInterval(t)},[page,selected]);
 const toggle=(key,id)=>setForm(f=>({...f,[key]:f[key].includes(id)?f[key].filter(x=>x!==id):[...f[key],id]}));
 const createConfig=async e=>{e.preventDefault();setBusy(true);setError("");try{await fetch(API+"/api/test-configurations",{method:"POST",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify({...form,target_id:Number(form.target_id),strategy_id:Number(form.strategy_id),attempts:Number(form.attempts)})}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()});await load();setPage("Test Configurations")}catch(e){setError(e.message)}finally{setBusy(false)}};
 const launch=async config=>{setBusy(true);try{const c=await fetch(API+"/api/campaigns",{method:"POST",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify({name:`${config.name} Campaign`,config_id:config.id})}).then(r=>r.json());await fetch(API+`/api/campaigns/${c.id}/start`,{method:"POST",headers});setSelected(c.id);setPage("Campaigns");await load()}finally{setBusy(false)}};
 const openRuns=async c=>{setSelected(c.id);setData(d=>({...d,runs:[]}));try{setData(d=>({...d,runs:await getJson(`campaigns/${c.id}/runs`)}))}catch(e){setError(e.message)}};
 const nav=["Dashboard","Providers","Targets","Scenarios","Strategies","Test Configurations","Campaigns","Findings","Reports","Risk Register","Coverage","Trends","Security & Governance"];
 return <div className="app"><aside><div className="brand">AI <span>RED TEAM</span></div><div className="sub">Security Testing Platform</div>{nav.map(x=><button key={x} className={page===x?"nav active":"nav"} onClick={()=>setPage(x)}>{x}</button>)}</aside><main><header><div><div className="eyebrow">PHASE 2 · ORCHESTRATION</div><h1>{page}</h1></div><button className="primary" disabled={busy} onClick={()=>setPage("Test Configurations")}>＋ New Test Configuration</button></header>{error&&<div className="error">{error}</div>}
 {page==="Dashboard"&&<><div className="cards"><Card t="Providers" v={data.providers.length}/><Card t="Targets" v={data.targets.length}/><Card t="Scenarios" v={data.scenarios.length}/><Card t="Open Findings" v={data.summary.open}/></div><div className="riskbar"><b>Risk posture</b><span>Critical {data.summary.critical}</span><span>High {data.summary.high}</span><span>Medium {data.summary.medium}</span><span>Avg score {data.summary.average_score}</span></div><Panel title="Execution Pipeline"><div className="pipeline"><span>Target</span>→<span>Scenario Planner</span>→<span>Strategy</span>→<span>Provider Fan-out</span>→<span>Normalized Result</span></div></Panel></>}
 {page==="Providers"&&<Panel title="Provider Registry">{data.providers.map(p=><Row key={p.id} title={p.name} detail={`${p.enabled?"ENABLED":"DISABLED"} · ${p.execution_modes.join(", ")} · ${p.capabilities.join(", ")}`}/>)}</Panel>}
 {page==="Targets"&&<Panel title="Authorized Targets">{data.targets.map(t=><Row key={t.id} title={t.name} detail={`${t.target_type} · ${t.endpoint} · ${t.capabilities.join(", ")}`}/>)}</Panel>}
 {page==="Scenarios"&&<Panel title="Scenario Library">{data.scenarios.map(s=><Row key={s.id} title={s.name} detail={`${s.key} · ${s.category} · ${s.severity} · ${s.supported_surfaces.join(", ")}`}/>)}</Panel>}
 {page==="Strategies"&&<Panel title="Execution Strategies">{data.strategies.map(s=><Row key={s.id} title={s.name} detail={JSON.stringify(s.config)}/>)}</Panel>}
 {page==="Test Configurations"&&<ConfigBuilder form={form} setForm={setForm} data={data} toggle={toggle} submit={createConfig} busy={busy}/>} 
 {page==="Campaigns"&&<Campaigns data={data} selected={selected} openRuns={openRuns} launch={launch}/>} 
 {page==="Findings"&&<Findings findings={data.findings}/>} {page==="Security & Governance"&&<SecurityGovernance/>} {page==="Reports"&&<Reports data={data}/>} {page==="Risk Register"&&<RiskRegister/>} {page==="Coverage"&&<Coverage/>} {page==="Trends"&&<Trends/>}
 </main></div>}
function Findings({findings}){return <Panel title="Findings & Risk Intelligence">{findings.length?findings.map(f=><div className="finding" key={f.id}><div><strong>{f.title}</strong><small>{f.category} · MITRE {f.mitre_atlas.join(", ")||"—"} · OWASP {f.owasp_llm.join(", ")||"—"}</small></div><div className="risk"><b>{f.risk_score}</b><em className={f.severity.toLowerCase()}>{f.severity}</em></div><p>{f.recommendation}</p></div>):<p className="muted">No findings yet. Launch a campaign to populate risk intelligence.</p>}</Panel>} function Reports({data}){const [report,setReport]=useState(null);const load=async()=>{if(!data.campaigns[0])return;setReport(await getJson(`reports/${data.campaigns[0].id}`))};return <Panel title="Executive Reports"><button className="secondary" onClick={load}>Generate latest campaign report</button>{report&&<pre className="report">{JSON.stringify(report,null,2)}</pre>}</Panel>} function Card({t,v}){return <div className="card"><span>{t}</span><b>{v}</b></div>}function Panel({title,children}){return <section className="panel"><h2>{title}</h2>{children}</section>}function Row({title,detail}){return <div className="row"><strong>{title}</strong><small>{detail}</small></div>}
function ConfigBuilder({form,setForm,data,toggle,submit,busy}){return <form className="panel builder" onSubmit={submit}><h2>Build Test Configuration</h2><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Agent Security Baseline"/></label><label>Target<select required value={form.target_id} onChange={e=>setForm({...form,target_id:e.target.value})}><option value="">Select target</option>{data.targets.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div><b>Providers</b><div className="chips">{data.providers.map(x=><button type="button" key={x.id} className={form.provider_ids.includes(x.id)?"chip selected":"chip"} onClick={()=>toggle("provider_ids",x.id)}>{x.name}</button>)}</div></div><div><b>Scenarios</b><div className="chips">{data.scenarios.map(x=><button type="button" key={x.id} className={form.scenario_ids.includes(x.id)?"chip selected":"chip"} onClick={()=>toggle("scenario_ids",x.id)}>{x.key} · {x.name}</button>)}</div></div><label>Strategy<select required value={form.strategy_id} onChange={e=>setForm({...form,strategy_id:e.target.value})}><option value="">Select strategy</option>{data.strategies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Attempts<input type="number" min="1" max="20" value={form.attempts} onChange={e=>setForm({...form,attempts:e.target.value})}/></label><button className="primary" disabled={busy||!form.provider_ids.length||!form.scenario_ids.length}>Save Configuration</button></form>}
function Campaigns({data,selected,openRuns,launch}){const c=data.campaigns.find(x=>x.id===selected);return <div className="split"><Panel title="Campaigns">{data.campaigns.map(x=><div className="campaign" key={x.id} onClick={()=>openRuns(x)}><strong>{x.name}</strong><small>{x.status} · {x.completed_tests}/{x.total_tests||"…"} tests</small></div>)}{data.configs.length>0&&<button className="secondary" onClick={()=>launch(data.configs[0])}>▶ Launch latest configuration</button>}</Panel><Panel title={c?`Run Details · ${c.name}`:"Run Details"}>{c?<><div className="progress"><div style={{width:`${c.total_tests?Math.round(c.completed_tests/c.total_tests*100):0}%`}}/></div><p>{c.status} · {c.completed_tests}/{c.total_tests} completed</p>{data.runs.map(r=><div className="run" key={r.id}><b>{r.provider}</b><span>{r.scenario} · attempt {r.attempt}</span><em className={r.success?"bad":"ok"}>{r.success?`FINDING · ${r.severity}`:"PASS"}</em></div>)}</>:<p className="muted">Select a campaign to inspect normalized test runs.</p>}</Panel></div>}

function RiskRegister(){const[rows,setRows]=useState([]);const[busy,setBusy]=useState(false);const load=()=>getJson("governance/risk-register").then(setRows);useEffect(load,[]);const close=async id=>{setBusy(true);await fetch(API+`/api/governance/risk-register/${id}`,{method:"PUT",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify({status:"RESOLVED",owner:"Security Team"})});await load();setBusy(false)};return <Panel title="Risk Register"><div className="toolbar"><button className="secondary" onClick={()=>fetch(API+"/api/governance/export.csv",{headers}).then(r=>r.blob()).then(b=>{const u=URL.createObjectURL(b);window.open(u)})}>Export CSV</button></div>{rows.map(r=><div className="finding" key={r.finding_id}><div><strong>#{r.finding_id} · {r.title}</strong><small>{r.category} · {r.owner||"Unassigned"} · {r.remediation_status}</small></div><div className="risk"><b>{r.risk_score}</b><em className={r.severity.toLowerCase()}>{r.severity}</em></div><p>{r.recommendation}</p>{r.status!=="RESOLVED"&&<button className="secondary" disabled={busy} onClick={()=>close(r.finding_id)}>Mark resolved</button>}</div>)}</Panel>}
function Coverage(){const[x,setX]=useState(null);useEffect(()=>{getJson("governance/coverage").then(setX)},[]);return <Panel title="Attack Coverage"><button className="secondary" onClick={()=>getJson("governance/coverage").then(setX)}>Refresh</button>{x&&<><div className="cards"><Card t="Scenario Coverage" v={`${x.coverage_pct}%`}/><Card t="Tested Scenarios" v={`${x.tested_scenarios}/${x.total_scenarios}`}/></div>{x.categories.map(c=><div className="row" key={c.category}><strong>{c.category}</strong><small>{c.tested}/{c.total} tested · {c.findings} findings · {c.coverage_pct}% coverage</small></div>)}</>}</Panel>}
function Trends(){const[x,setX]=useState([]);useEffect(()=>{getJson("governance/trends").then(setX)},[]);return <Panel title="Risk Trends"><div className="trendtable"><div className="trendhead"><b>Campaign</b><b>Tests</b><b>Findings</b><b>Critical</b><b>High</b><b>Avg Risk</b></div>{x.map(r=><div className="trendrow" key={r.campaign_id}><span>{r.campaign}</span><span>{r.tests}</span><span>{r.findings}</span><span>{r.critical}</span><span>{r.high}</span><span>{r.avg_risk}</span></div>)}</div></Panel>}

function SecurityGovernance(){const[me,setMe]=useState(null),[policies,setPolicies]=useState([]),[schedules,setSchedules]=useState([]),[audit,setAudit]=useState([]),[busy,setBusy]=useState(false);const load=async()=>{try{const[m,p,s,a]=await Promise.all([getJson("auth/me"),getJson("platform/policies"),getJson("platform/schedules"),getJson("platform/audit?limit=50")]);setMe(m);setPolicies(p);setSchedules(s);setAudit(a)}catch(e){}};useEffect(()=>{load()},[]);const seedPolicy=async()=>{setBusy(true);await fetch(API+"/api/platform/policies",{method:"POST",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify({name:"default-ai-security-policy",description:"Baseline enterprise AI security controls",rules:{max_risk_score:80,require_mitre_mapping:true,require_evidence:true,block_critical_release:true}})});await load();setBusy(false)};return <div className="split"><Panel title="Identity & Access">{me&&<><div className="card"><span>Authenticated principal</span><b>{me.name}</b><small>Role: {me.role}</small></div><p className="muted">API access is protected by X-API-Key. Configure keys through environment variables and never commit production secrets.</p></>}</Panel><Panel title="Policy as Code"><button className="secondary" disabled={busy} onClick={seedPolicy}>＋ Create baseline policy</button>{policies.map(p=><div className="row" key={p.id}><strong>{p.name}</strong><small>{p.enabled?"ENABLED":"DISABLED"} · {p.description}</small></div>)}</Panel><Panel title="Scheduled Assessments"><p className="muted">Schedules are persisted independently from workers so scheduling can be operated without coupling it to the API process.</p>{schedules.length?schedules.map(s=><div className="row" key={s.id}><strong>{s.name}</strong><small>Config #{s.config_id} · {s.cron} · {s.enabled?"ENABLED":"DISABLED"}</small></div>):<p className="muted">No schedules configured.</p>}</Panel><Panel title="Audit Trail"><div className="trendtable"><div className="trendhead"><b>Actor</b><b>Role</b><b>Action</b><b>Resource</b><b>Status</b><b>Time</b></div>{audit.map(a=><div className="trendrow" key={a.id}><span>{a.actor}</span><span>{a.role}</span><span>{a.action}</span><span>{a.resource}</span><span>{a.status_code}</span><span>{new Date(a.created_at).toLocaleString()}</span></div>)}</div></Panel></div>}

createRoot(document.getElementById("root")).render(<App/>);
